---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- .idea/
- coverage/
- dist/
- node_modules/
- test/
