env:
  global:
    - CC_TEST_REPORTER_ID=a5381b7241fae901316b0abe96701fa9504cd9e55d945a42e2ad00f8f0499cc0

language: node_js
node_js:
  - "9"
  - "8"
  - "6"
  - "10"
before_script:
  - npm install -g grunt-cli
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: grunt test && grunt cover
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT